# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SHSH Wallet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SHSH Wallet
  pod 'ObjectMapper', '~> 3.5'
  pod 'EasyTipView', '~> 2.0.4'

end
